spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/quickbite_notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:quickbite_notification}
    password: ${SPRING_DATASOURCE_PASSWORD:quickbite_notification}
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: 10000
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
